[package]
name = "FD-general-report"
version = "0.1.0"
entrypoint = "src/lib.typ"
keywords = ["Formal Document", "Report", "General", "Report Template", "General Report"]
categories = ["report"]
authors = [
    "Jarem Joseph Gallegos Yanarico @jaremgallegos",
]
license = "MIT"
description = "General Formal Report for Typst"

[template]
path = "template"
entrypoint = "main.typ"